import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('31.220.18.39', 22, 'root', 'Travis18456916#')
stdin, stdout, stderr = ssh.exec_command('docker ps -a --filter name=redis --format "{{.Names}}: {{.Status}}"')
print("Redis containers:")
print(stdout.read().decode())
print(stderr.read().decode())
stdin, stdout, stderr = ssh.exec_command('docker compose -f /root/virtual-tryon/docker-compose.backend.yml ps')
print("\nBackend compose ps:")
print(stdout.read().decode())
ssh.close()