http:
  routers:
    lookitry-api:
      rule: "Host(`api.lookitry.com`)"
      service: lookitry-api
      tls:
        certresolver: mytlschallenge
      middlewares:
        - lookitry-cors
    lookitry-api-web:
      rule: "Host(`api.lookitry.com`)"
      service: lookitry-api
      entrypoints: web
  services:
    lookitry-api:
      loadBalancer:
        servers:
          - url: "http://lookitry-backend:3001"
  middlewares:
    lookitry-cors:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        accessControlAllowOriginList:
          - "*"
        accessControlAllowHeaders:
          - "*"
        accessControlExposeHeaders:
          - "*"
        accessControlAllowCredentials: true