name: Sync Plugin to WordPress

on:
  push:
    branches: [main]
    paths:
      - 'lookitry-woocommerce/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 92.112.189.47
          username: u639440667
          password: ${{ secrets.FTP_PASS }}
          port: 65002
          source: "./lookitry-woocommerce/*"
          target: "/home/u639440667/domains/wilkiedevs.com/public_html/wp-content/plugins/lookitry-woocommerce/"
          strip_components: 1
